#!/bin/bash

# Script para configurar variables de firma para el proceso de build
# Este script crea un archivo local.properties con las configuraciones de firma

echo "Configurando propiedades de firma para el build..."

# Creación o actualización del archivo local.properties
cat > ./local.properties << EOF
# Generated by Bitbucket Pipelines
sdk.dir=$ANDROID_HOME

# Keystore configuration
krediya.keystore.file=$BITBUCKET_CLONE_DIR/keystore/krediya-keystore.jks
krediya.keystore.password=$KEYSTORE_PASSWORD
krediya.key.alias=$KEYSTORE_ALIAS
krediya.key.password=$KEY_PASSWORD

# Disable baseline profiles for CI/CD builds by setting this property
# This will be picked up by the Gradle script
disableBaselineProfiles=true
EOF

echo "Configuración de firma completada correctamente."